logging:
  level:
    web: DEBUG

spring:
  kafka:
    bootstrap-servers: 192.168.0.12:9092
    consumer:
      group-id: furrify
    producer:
      retries: 3
  datasource:
    driverClassName: org.h2.Driver
    username: 'sa'
    password: 'password'
    url: jdbc:h2:mem:testdb
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka"

server:
  port: 8081

keycloak:
  auth-server-url: http://localhost:6565/auth
  realm: dev
  resource: keycloak-test
  public-client: true
  principal-attribute: preferred_username
  bearer-only: true
  use-resource-role-mappings: true